"""empty message

Revision ID: 459d52bffdb2
Revises: 
Create Date: 2025-06-10 21:45:09.427669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459d52bffdb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('certification_id', sa.Integer(), nullable=False),
    sa.Column('certification_name', sa.String(length=80), nullable=False),
    sa.Column('certification_description', sa.String(length=900), nullable=False),
    sa.Column('drive_link', sa.String(length=500), nullable=True),
    sa.Column('certificate', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('certification_id'),
    sa.UniqueConstraint('certification_id'),
    sa.UniqueConstraint('certification_name')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=80), nullable=False),
    sa.Column('project_description', sa.String(length=900), nullable=False),
    sa.Column('live_link', sa.String(length=500), nullable=True),
    sa.Column('git_link', sa.String(length=500), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('resume',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('resume_file', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('resume_id'),
    sa.UniqueConstraint('resume_id')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=80), nullable=False),
    sa.Column('skill_type', sa.String(length=900), nullable=False),
    sa.Column('logo', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('skill_id'),
    sa.UniqueConstraint('skill_id'),
    sa.UniqueConstraint('skill_name')
    )
    op.create_table('work',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('work_name', sa.String(length=80), nullable=False),
    sa.Column('work_description', sa.String(length=900), nullable=False),
    sa.Column('work_type', sa.String(length=900), nullable=False),
    sa.Column('certificate', sa.LargeBinary(), nullable=True),
    sa.Column('drive_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('work_id'),
    sa.UniqueConstraint('work_description'),
    sa.UniqueConstraint('work_id'),
    sa.UniqueConstraint('work_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    op.drop_table('skills')
    op.drop_table('resume')
    op.drop_table('projects')
    op.drop_table('certifications')
    # ### end Alembic commands ###
