"""empty message

Revision ID: 6d52345a65b0
Revises: 456fbe0486c0
Create Date: 2025-06-11 11:54:35.434057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d52345a65b0'
down_revision = '456fbe0486c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pwd',
    sa.Column('pwd_id', sa.Integer(), nullable=False),
    sa.Column('passd', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('pwd_id'),
    sa.UniqueConstraint('passd'),
    sa.UniqueConstraint('pwd_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pwd')
    # ### end Alembic commands ###
