"""empty message

Revision ID: 93921476a43a
Revises: 6d52345a65b0
Create Date: 2025-06-11 12:08:28.947899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93921476a43a'
down_revision = '6d52345a65b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pwd',
    sa.Column('pwd_id', sa.INTEGER(), nullable=False),
    sa.Column('passd', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('pwd_id'),
    sa.UniqueConstraint('passd'),
    sa.UniqueConstraint('pwd_id')
    )
    # ### end Alembic commands ###
